services:
  app:
    build:
      args:
        user: laravel_course
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel_course_app_image
    container_name: laravel_course_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_course_net
    depends_on:
      - db
  web:
    image: nginx:latest
    container_name: laravel_course_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel_course_net
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: laravel_course_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=laravel_course
      - MYSQL_DATABASE=laravel_course
      - MYSQL_USER=laravel_course
      - MYSQL_PASSWORD=laravel_course
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_course_net
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_course_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=laravel_course
      - PMA_PASSWORD=laravel_course
    networks:
      - laravel_course_net
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: laravel_course_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_course_net

volumes:
  db_data:
    driver: local
networks:
  laravel_course_net: